### PR TITLE
fix(video-format): use maxFrameRate param

### LINKED ISSUE #235: Frames Per Second parameter
Hi there, peeking thru the code, Min FPS is set to 30 FPS.. 
However, the TV broadcasts which is most of my recordings, are mostly (here in Europe at least :) ) 25FPS..
The best bet might be to let users decide this at the options page: 25,30,50,60 whatever..
Thank you.

### PR DESCRIPTION
**Pull request by ww24**
- fix #235

### CODE REVIEW

File: src/offscreen.ts [hunk 1]
```diff
@@ -78,8 +78,8 @@ async function startRecording(startRecording: StartRecording) {
                 chromeMediaSourceId: startRecording.streamId,
                 maxWidth: size.width,
                 maxHeight: size.height,
-                minFrameRate: videoFormat.frameRate,
-            }
+                maxFrameRate: videoFormat.frameRate,
```
Comment (ww24) [inline src/offscreen.ts:81]: To tell the browser the exact frame rate, you need to specify `maxFrameRate`.

File: src/element/util.ts [hunk 2]
```diff
@@ -28,7 +28,7 @@ export function deepMerge<T>(obj1: T, obj2: T): T {
         if (!Object.hasOwn(obj2 as object, k)) continue
         if (obj1[k] instanceof Object && obj2[k] instanceof Object) {
             res[k] = deepMerge(obj1[k], obj2[k])
-        } else {
+        } else if (obj2[k] != null) {
```
Comment (ww24) [inline src/element/util.ts:31]: We took null into consideration because if the value is saved as null for some reason, it cannot be restored.
