### PR TITLE
fix(message): fix inappropriate message handling

### LINKED ISSUE #550: InvalidStateError in start-recording process.
```
InvalidStateError: An operation that depends on state cached in an interface object was made but the state had changed since it was read from disk.
```

https://fs.spec.whatwg.org/

### PR DESCRIPTION
**Pull request by ww24**
- fix #550 

This pull request refactors how message handling and responses are managed across several components, primarily to ensure that asynchronous message handlers do not inadvertently interfere with other message contexts by returning truthy values or Promises. It also simplifies and standardizes the message handling API, removes unnecessary wrapper types, and improves error handling and testability.

**Refactoring and Standardization of Message Handling:**

* Message handlers in `Cropping`, `CroppingPreview`, and `RecordList` components are now synchronous and do not return Promises or truthy values, preventing interference with other message contexts. Asynchronous work is now done inside immediately-invoked async functions with proper error logging. [[1]](diffhunk://#diff-81dabb420a898a953e6bf91f030fd1ed06c8c37f5e7c4f4d81062a8671fe66a3R94-R98) [[2]](diffhunk://#diff-701fd87d451b3ceea98b26bf1e7a19e57d4ad6ef2305135de6b1063291885bc5L165-R169) [[3]](diffhunk://#diff-dea6f71f0c44b97d2a839ca7823249ca816ea17b0ace97cd46cfff532a03cdd3L162-R166)
* The `offscreen_handler.ts` API is simplified: the custom `HandleOffscreenMessageResult` wrapper type is removed, and handlers now return either the direct response or `void`. [[1]](diffhunk://#diff-2cd9574db7de00aeee9efe2ae07c8b53c29c954d46d5b9078efe3388cf8afaebL43-L48) [[2]](diffhunk://#diff-2cd9574db7de00aeee9efe2ae07c8b53c29c954d46d5b9078efe3388cf8afaebL58-R52) [[3]](diffhunk://#diff-2cd9574db7de00aeee9efe2ae07c8b53c29c954d46d5b9078efe3388cf8afaebL87-R81) [[4]](diffhunk://#diff-2cd9574db7de00aeee9efe2ae07c8b53c29c954d46d5b9078efe3388cf8afaebL118-R115) [[5]](diffhunk://#diff-2cd9574db7de00aeee9efe2ae07c8b53c29c954d46d5b9078efe3388cf8afaebL144-R140) [[6]](diffhunk://#diff-2cd9574db7de00aeee9efe2ae07c8b53c29c954d46d5b9078efe3388cf8afaebL166-L212)

**Service Worker Message Handling Improvements:**

* The service worker now uses a new `createMessageListener` utility, which standardizes error handling and ensures correct response semantics for fire-and-forget and response-returning messages. The previous `handleMessage` function is refactored for clarity and testability. [[1]](diffhunk://#diff-9a8dfe07c2bfeb25a7bcb4e293c44857c0bbbfc3417c31f1dc9d1d3482864216L25-R24) [[2]](diffhunk://#diff-9a8dfe07c2bfeb25a7bcb4e293c44857c0bbbfc3417c31f1dc9d1d3482864216L422-R428) [[3]](diffhunk://#diff-3387c9a641bb064c8f2a7ab711fd42c52a69d02fe3ca71c99dd0a238b44e5bedL25-R131)
* The service worker message handler's result type is updated to clearly distinguish between response and fire-and-forget messages, and to avoid returning Promises from fire-and-forget handlers.

**Bug Fixes and Behavior Changes:**

* The message listener in `offscreen.ts` now sends the correct response object, fixing a potential bug where the wrong property was returned.

**Test Updates:**

* Tests are updated to reflect the new handler return values, removing references to the obsolete `.response` property. [[1]](diffhunk://#diff-430b24f1c6b6b7cd707bc3427ed61d67bac46459739d4e5151415537d59a84d4L178-R178) [[2]](diffhunk://#diff-430b24f1c6b6b7cd707bc3427ed61d67bac46459739d4e5151415537d59a84d4L195-R196) [[3]](diffhunk://#diff-430b24f1c6b6b7cd707bc3427ed61d67bac46459739d4e5151415537d59a84d4L214-R214) [[4]](diffhunk://#diff-430b24f1c6b6b7cd707bc3427ed61d67bac46459739d4e5151415537d59a84d4L229-R229)
* Test imports are updated to use the new `createMessageListener` for improved testability.

### CODE REVIEW

File: src/element/croppingPreview.ts [hunk 1]
```diff
@@ -162,8 +162,9 @@ export class CroppingPreview extends LitElement {
         }
     }
 
-    private handleMessage = async (message: PreviewFrameMessage) => {
```
Comment (ww24) [inline src/element/croppingPreview.ts:165]: > Keep in mind that an async function as a listener will always return a promise, even without a return statement. If an async listener does not return a value its promise implicitly resolves to undefined, and null is sent as the response to the sender. This can cause unexpected behavior when there are multiple listeners
https://developer.chrome.com/docs/extensions/develop/concepts/messaging
